FROM python:3
RUN export PIP_TRUSTED_HOST=https://pypi.python.org/simple && pip install checkov
RUN export PIP_TRUSTED_HOST="https://pypi.python.org/simple" && pip install checkov
RUN export PIP_TRUSTED_HOST='https://pypi.python.org/simple' && pip install checkov

RUN PIP_TRUSTED_HOST=https://pypi.python.org/simple pip install checkov
RUN PIP_TRUSTED_HOST="https://pypi.python.org/simple" pip install checkov
RUN PIP_TRUSTED_HOST='https://pypi.python.org/simple' pip install checkov

RUN PIP_TRUSTED_HOST=https://pypi.python.org/simple CHECKOV=AWESOME pip install checkov
RUN PIP_TRUSTED_HOST="https://pypi.python.org/simple" CHECKOV="AWESOME" pip install checkov
RUN PIP_TRUSTED_HOST='https://pypi.python.org/simple' CHECKOV='AWESOME' pip install checkov

RUN CHECKOV=AWESOME PIP_TRUSTED_HOST=https://pypi.python.org/simple pip install checkov
RUN CHECKOV="AWESOME" PIP_TRUSTED_HOST="https://pypi.python.org/simple" pip install checkov
RUN CHECKOV='AWESOME' PIP_TRUSTED_HOST='https://pypi.python.org/simple' pip install checkov

RUN TEST_123="456" PIP_TRUSTED_HOST=https://pypi.python.org/simple geordi="la forge" pip install checkov
RUN TEST_123='456' PIP_TRUSTED_HOST="https://pypi.python.org/simple" geordi='la forge' pip install checkov
RUN TEST_123=456 PIP_TRUSTED_HOST='https://pypi.python.org/simple' geordi="la forge" pip install checkov

RUN TEST_123="456" \
    PIP_TRUSTED_HOST=https://pypi.python.org/simple \
    EXAMPLE="VAR" \
    pip install checkov
RUN TEST_123='456' \
    PIP_TRUSTED_HOST="https://pypi.python.org/simple" \
    EXAMPLE='VAR' \
    pip install checkov
RUN \
    TEST_123=456\
    PIP_TRUSTED_HOST='https://pypi.python.org/simple' \
    EXAMPLE="VAR" \
    pip install checkov
