FROM python:3
ENV PIP_TRUSTED_HOST https://pypi.python.org/simple
ENV PIP_TRUSTED_HOST=https://pypi.python.org/simple
ENV PIP_TRUSTED_HOST="https://pypi.python.org/simple"
ENV PIP_TRUSTED_HOST='https://pypi.python.org/simple'
ARG PIP_TRUSTED_HOST=https://pypi.python.org/simple
ARG PIP_TRUSTED_HOST="https://pypi.python.org/simple"
ARG PIP_TRUSTED_HOST='https://pypi.python.org/simple'
ARG PIP_TRUSTED_HOST https://pypi.python.org/simple
ENV LOL=123 PIP_TRUSTED_HOST=https://pypi.python.org/simple
ENV PIP_TRUSTED_HOST=https://pypi.python.org/simple LOL=123
ENV PIP_TRUSTED_HOST    https://pypi.python.org/simple
ARG PIP_TRUSTED_HOST    https://pypi.python.org/simple
