FROM alpine:3.5
RUN apk add --allow-untrusted python3
RUN apk --allow-untrusted add python3
RUN apk \
    --allow-untrusted \
    add python3
RUN apk \
    add python3 \
    --allow-untrusted
RUN echo "prodsec" && apk --allow-untrusted add python3
