metadata:
  id: "CKV_AZURE_230"
  name: "Ensure storage account is configured with SAS expiration policy"
  category: "GENERAL_SECURITY"

definition:
  and:
    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "shared_access_key_enabled"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "shared_access_key_enabled"
      operator: "equals_ignore_case"
      value: "false"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "sas_policy"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "sas_policy.expiration_period"
      operator: "length_greater_than"
      value: "0"
