metadata:
  id: "CKV2_AZURE_33"
  name: "Ensure storage account is configured with private endpoint"
  category: "GENERAL_SECURITY"

definition: 
  and:
    - cond_type: "filter"
      attribute: "resource_type"
      operator: "within"
      value:
        - "azurerm_storage_account"

    - cond_type: "connection"
      resource_types: 
        - "azurerm_storage_account"
      connected_resource_types:
        - "azurerm_private_endpoint"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "network_rules.default_action"
      operator: "equals_ignore_case"
      value: "Allow"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "network_rules.ip_rules"
      operator: "length_greater_than"
      value: 0