metadata:
  id: "CKV2_AZURE_31"
  name: "Ensure VNET subnet is configured with a Network Security Group (NSG)"
  category: "GENERAL_SECURITY"

definition:
  or:

  # Check if subnet & NSG are connected and present in the
  # "azurerm_subnet_network_security_group_association" block
    - and:
      - cond_type: "filter"
        attribute: "resource_type"
        operator: "within"
        value:
          - "azurerm_subnet"
      - cond_type: "connection"
        resource_types:
          - "azurerm_subnet"
        connected_resource_types:
          - "azurerm_network_security_group"
          - "azurerm_subnet_network_security_group_association"
        operator: "exists"

  # Ignore if subnet name is "GatewaySubnet" or "AzureFirewallSubnet"

    - cond_type: "attribute"
      resource_types: "azurerm_subnet"
      attribute: "name"
      operator: "equals_ignore_case"
      value: "GatewaySubnet"

    - cond_type: "attribute"
      resource_types: "azurerm_subnet"
      attribute: "name"
      operator: "equals_ignore_case"
      value: "AzureFirewallSubnet"

  # Ignore if service_delegation equals "Microsoft.Netapp/volumes"

    - cond_type: "attribute"
      resource_types: "azurerm_subnet"
      attribute: "delegation.service_delegation.name"
      operator: "equals_ignore_case"
      value: "Microsoft.Netapp/volumes"
