metadata:
  id: "CKV2_AZURE_32"
  name: "Ensure private endpoint is configured to key vault"
  category: "GENERAL_SECURITY"

definition:
  and:

    - cond_type: "filter"
      attribute: "resource_type"
      operator: "within"
      value:
        - "azurerm_key_vault"
    - cond_type: "connection"
      resource_types:
        - "azurerm_key_vault"
      connected_resource_types:
        - "azurerm_private_endpoint"
      operator: "exists"
