metadata:
  id: "CKV2_AZURE_36"
  name: "Ensure Azure automation account is configured with managed identity"
  category: "IAM"

definition:
  and:
    - cond_type: "attribute"
      resource_types: "azurerm_automation_account"
      attribute: "identity.type"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "azurerm_automation_account"
      attribute: "identity.type"
      operator: "number_of_words_not_equals"
      value: "0"

