metadata:
  id: "CKV_AZURE_229"
  name: "Ensure storage account is configured with Shared Key authorization"
  category: "GENERAL_SECURITY"

definition:
  and:
    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "shared_access_key_enabled"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "azurerm_storage_account"
      attribute: "shared_access_key_enabled"
      operator: "equals_ignore_case"
      value: "false"