metadata:
  id: CKV2_AZURE_27
  name: "Ensure Azure AD authentication is enabled for Azure SQL (MSSQL)"
  category: "GENERAL_SECURITY"

definition:
  and: 

    - cond_type: attribute
      resource_types: azurerm_mssql_server
      attribute: properties.administratorLogin
      operator: "exists"
