metadata:
  id: "CKV2_AZURE_45"
  name: "Ensure Azure SQL server is configured with private endpoint"
  category: "GENERAL_SECURITY"

definition:
  and:
    - cond_type: "filter"
      attribute: "resource_type"
      operator: "within"
      value:
        - "azurerm_mssql_server"

    - cond_type: "connection"
      resource_types:
        - "azurerm_mssql_server"
      connected_resource_types:
        - "azurerm_private_endpoint"
      operator: "exists"
