metadata:
  id: "CKV2_AZURE_7"
  name: "Ensure that Azure Active Directory Admin is configured"
  category: "GENERAL_SECURITY"
definition:
  and:
    - resource_types:
        - azurerm_sql_server
      connected_resource_types:
        - azurerm_sql_active_directory_administrator
      operator:  exists
      cond_type: connection
    - cond_type: filter
      attribute: resource_type
      value:
        - azurerm_sql_server
      operator: within

