metadata:
  id: "CKV2_AZURE_10"
  name: "Ensure that Microsoft Antimalware is configured to automatically updates for Virtual Machines"
  category: "GENERAL_SECURITY"
definition:
  and:
    - cond_type: filter
      attribute: resource_type
      value:
        - azurerm_virtual_machine
      operator: within
    - cond_type: connection
      operator: exists
      resource_types:
        - azurerm_virtual_machine
      connected_resource_types:
        - azurerm_virtual_machine_extension
    - cond_type: attribute
      attribute: type
      value: "IaaSAntimalware"
      operator: equals
      resource_types:
        - azurerm_virtual_machine_extension
    - cond_type: attribute
      attribute: publisher
      value: "Microsoft.Azure.Security"
      operator: equals
      resource_types:
        - azurerm_virtual_machine_extension
    - cond_type: attribute
      attribute: auto_upgrade_minor_version
      value: true
      operator: equals
      resource_types:
        - azurerm_virtual_machine_extension