from typing import NamedTuple


class PackageURL(NamedTuple):
    name: str | None = ...
    namespace: str | None = ...
    qualifiers: str | dict[str, str] | None = ...
    subpath: str | None = ...
    type: str | None = ...
    version: str | None = ...
