metadata:
  version: 0.2
  approach: define failing
  id: CKV_AWS_82
  name: Ensure Athena Workgroup should enforce configuration to prevent client disabling encryption
  category: GENERAL_SECURITY
  framework: cdk
scope:
  languages:
    - typescript
definition:

  pattern: |
    const $WORKGROUP: athena.CfnWorkGroup.WorkGroupConfigurationProperty = { <ANY> };
  conditions:
    - not_pattern: |
        const $WORKGROUP: athena.CfnWorkGroup.WorkGroupConfigurationProperty = { <ANY>, enforceWorkGroupConfiguration: true };
#    - not_pattern: |
#        $ARG = aws_cdk.aws_athena.CfnWorkGroup.WorkGroupConfigurationProperty(<ANY>, enforce_work_group_configuration=True , <ANY>)
#        <ANY>
#        aws_cdk.aws_athena.CfnWorkGroup(<ANY>, work_group_configuration=$ARG , <ANY>)