metadata:
  version: 0.2
  approach: define failing
  id: CKV_AWS_82
  name: Ensure Athena Workgroup should enforce configuration to prevent client disabling encryption
  category: GENERAL_SECURITY
  framework: cdk
scope:
  languages:
    - typescript
definition:

  pattern: |
    new athena.CfnWorkGroup(<ANY>, <ANY>, $WORKGROUP );
  conditions:
    - not_pattern: |
        const $WORKGROUP: athena.CfnWorkGroup.WorkGroupConfigurationProperty = { <ANY>, enforceWorkGroupConfiguration: true, <ANY> };
        <ANY>
        const $VAR1 = new athena.CfnWorkGroup(<ANY>, <ANY>, $WORKGROUP );
    - not_pattern:
        source: |
          { <ANY>, enforceWorkGroupConfiguration: true, <ANY> }
        sink: new athena.CfnWorkGroup(<ANY>, <ANY>, <SOURCE> );
    - not_pattern: |
        new athena.CfnWorkGroup(<ANY>, <ANY>, {<ANY>, enforceWorkGroupConfiguration: true });
