metadata:
  version: 0.2
  approach: define failing
  id: CKV_AWS_45
  name: Ensure no hard-coded secrets exist in lambda environment
  category: SECRETS
  framework: cdk
scope:
  languages:
    - typescript
definition:
  or:
    - patterns:
        or:
          - pattern: |
              new $PACKAGE.aws_lambda.Function(<ANY> ,<ANY>, { <ANY>, environment: { $ARG1:'$ARG2' }, <ANY> })
          - pattern: |
              new $PACKAGE.aws_lambda.CfnFunction(<ANY> ,<ANY>, { <ANY>, environment: { <ANY>, variables: { $ARG1:'$ARG2'}, <ANY>}, <ANY> })
          - pattern: |
              new $PACKAGE.aws_sam.CfnFunction(<ANY> ,<ANY>, { <ANY>, environment: { <ANY>, variables: { $ARG1:'$ARG2'}, <ANY>}, <ANY> })
      conditions:
        - metavariable: $PACKAGE
          comparison: $PACKAGE == "aws-cdk-lib"
    - pattern: |
        $X = { <ANY>, environment: { $ARG1:'$ARG2' }, <ANY> }
      conditions:
        - metavariable: $X
          type: aws-cdk-lib.aws_lambda.FunctionProps
    - pattern: |
        $X =  { <ANY>, environment: { <ANY>, variables: { $ARG1:'$ARG2'}, <ANY>}, <ANY> }
      conditions:
        - metavariable: $X
          type: aws-cdk-lib.aws_lambda.CfnFunctionProps
    - pattern: |
        $X = { <ANY>, environment: { <ANY>, variables: { $ARG1:'$ARG2'}, <ANY>}, <ANY> }
      conditions:
        - metavariable: $X
          type: aws-cdk-lib.aws_sam.CfnFunctionProps
