metadata:
  version: 0.2
  approach: define failing
  id: CKV_AWS_123
  name: Ensure that VPC Endpoint Service is configured for Manual Acceptance
  category: NETWORKING
  framework: cdk
scope:
  languages:
    - typescript
definition:
  pattern: new $AWS.CfnVPCEndpointService(<ANY>)
  conditions:
    - not_pattern: |
        new $AWS.CfnVPCEndpointService(<ANY>, {<ANY>, acceptanceRequired: true, <ANY>} ,<ANY>)