metadata:
  id: "CKV2_IBM_5"
  name: "Ensure Service ID creation is restricted in account settings"
  category: "IAM"

definition:
  and:

    - cond_type: "attribute"
      resource_types: "ibm_iam_account_settings"
      attribute: "restrict_create_service_id"
      operator: "exists"

    - cond_type: "attribute"
      resource_types: "ibm_iam_account_settings"
      attribute: "restrict_create_service_id"
      operator: "equals_ignore_case"
      value: "RESTRICTED"
