FROM node:18
RUN yarn config set strict-ssl="false"
RUN yarn config set "strict-ssl"="false"
RUN yarn config set 'strict-ssl'="false"

RUN yarn config set strict-ssl='false'
RUN yarn config set "strict-ssl"='false'
RUN yarn config set 'strict-ssl'='false'

RUN yarn config set strict-ssl=false
RUN yarn config set "strict-ssl"=false
RUN yarn config set 'strict-ssl'=false

RUN yarn config set strict-ssl false
RUN yarn config set "strict-ssl" false
RUN yarn config set 'strict-ssl' false

RUN yarn      config     set      strict-ssl    "false"
RUN yarn      config     set     "strict-ssl"   'false'
RUN yarn      config     set     'strict-ssl'    false

RUN yarn set strict-ssl false
RUN yarn set "strict-ssl" false
RUN yarn set 'strict-ssl' false

RUN yarn      set      strict-ssl    'false'
RUN yarn      set     "strict-ssl"    false
RUN yarn      set     'strict-ssl'   "false"
