FROM node:18
RUN npm config set strict-ssl=false
RUN npm config set "strict-ssl"=false
RUN npm config set 'strict-ssl'=false

RUN npm config set strict-ssl="false"
RUN npm config set "strict-ssl"="false"
RUN npm config set 'strict-ssl'="false"

RUN npm config set strict-ssl='false'
RUN npm config set "strict-ssl"='false'
RUN npm config set 'strict-ssl'='false'

RUN npm config set strict-ssl false
RUN npm config set "strict-ssl" false
RUN npm config set 'strict-ssl' false

RUN npm      config     set      strict-ssl     false
RUN npm      config     set     "strict-ssl"   "false"
RUN npm      config     set     'strict-ssl'   'false'

RUN npm set strict-ssl false
RUN npm set "strict-ssl" false
RUN npm set 'strict-ssl' false

RUN npm      set      strict-ssl     false
RUN npm      set     "strict-ssl"   "false"
RUN npm      set     'strict-ssl'   'false'

RUN npm c set strict-ssl false