FROM debian:bullseye
RUN apt-get install --force-yes python3
RUN apt-get --force-yes install python3
RUN apt-get \
    --force-yes \
    install python3
RUN apt-get \
    install python3 \
    --force-yes
RUN echo "prodsec" && apt-get --force-yes install python3
