apiVersion: v1
kind: ConfigMap
metadata:
  name: whorfconfig
  namespace: bridgecrew
data:
  # debug will save the parsed manifests to the file system for later inspection 
  debug: "no"
  # kubernetes related config
  k8s.properties: |
    ignores-namespaces=kube-system,bridgecrew
