FROM fedora:rawhide
RUN rpm -i --nogpgcheck python3.rpm
RUN rpm --nogpgcheck -i python3.rpm
RUN rpm \
    --nogpgcheck \
    -i python3.rpm
RUN rpm \
    -i python3.rpm \
    --nogpgcheck
RUN echo "prodsec" && rpm --nogpgcheck -i python3.rpm
