FROM debian:bullseye
RUN apt-get install --allow-unauthenticated python3
RUN apt-get --allow-unauthenticated install python3
RUN apt-get \
    --allow-unauthenticated \
    install python3
RUN apt-get \
    install python3 \
    --allow-unauthenticated
RUN echo "prodsec" && apt-get --allow-unauthenticated install python3
