FROM fedora:rawhide

RUN yum config-manager --save --setopt=sslverify=0
RUN yum           config-manager           --save           --setopt=sslverify=0

RUN dnf config-manager --save --setopt=sslverify=0
RUN dnf           config-manager           --save           --setopt=sslverify=0
