metadata:
  version: 0.2
  approach: define failing
  id: CKV_AWS_45
  name: Ensure no hard-coded secrets exist in lambda environment
  category: SECRETS
  framework: cdk
scope:
  languages:
    - python
definition:
  patterns:
    or:
      - pattern: |
            aws_cdk.aws_lambda.Function(<ANY>, environment={'$ARG1':'$ARG2'} ,<ANY>)
      - pattern: |
            aws_cdk.aws_sam.CfnFunction(<ANY>, environment={'$ARG1':'$ARG2'} ,<ANY>)