metadata:
  id: "CKV_K8S_XXX"
  name: "ClusterRoleBinding should not allow privilege escalation to a ServiceAccount or Node on other ClusterRoleBinding"
  category: "KUBERNETES"
  # TODO fill
definition:
  and:
    - cond_type: filter
      value:
        - ClusterRoleBinding
      operator: within
      attribute: kind
    - cond_type: connection  # Filter ClusterRoleBiding with connection to ClusterRole
      operator: exists
      resource_types:
        - ClusterRole
      connected_resource_types:
        - ClusterRoleBinding
    - and:  # ClusterRole does not contain `clusterrolebindings/rolebinding/*` in `rule.resources` and `bind/*` in `rule.verbs`
      - cond_type: attribute
        attribute: rules.resources
        operator: not_intersects
        value:
          - 'clusterrolebindings'
          - 'rolebindings'
          - '*'
        resource_types:
          - ClusterRole
      - cond_type: attribute
        attribute: rules.verbs
        operator: not_contains
        value:
          - 'bind'
          - '*'
        resource_types:
          - ClusterRole