metadata:
  id: "CKV2_K8S_3"
  name: "No ServiceAccount/Node should have `impersonate` permissions for groups/users/service-accounts"
  category: "KUBERNETES"
definition:
  and:
    - cond_type: filter
      value:
        - ClusterRoleBinding
        - RoleBinding
      operator: within
      attribute: kind
    - or:
        - cond_type: connection
          operator: not_exists
          resource_types:
            - ClusterRoleBinding
            - RoleBinding
          connected_resource_types:
            - ClusterRole
            - Role
        - cond_type: attribute
          attribute: 'subjects.*.kind'
          operator: not_within
          value:
            - 'Node'
            - 'ServiceAccount'
          resource_types:
            - ClusterRoleBinding
            - RoleBinding
        - and:
            - cond_type: connection
              operator: exists
              resource_types:
                - ClusterRoleBinding
                - RoleBinding
              connected_resource_types:
                - ClusterRole
                - Role
            - or:
              - cond_type: attribute
                attribute: rules.resources
                operator: not_intersects
                value:
                  - 'groups'
                  - 'users'
                  - 'serviceaccounts'
                  - '*'
                resource_types:
                  - ClusterRole
                  - Role
              - cond_type: attribute
                attribute: rules.verbs
                operator: not_intersects
                value:
                  - 'impersonate'
                  - '*'
                resource_types:
                  - ClusterRole
                  - Role
