FROM python:3
RUN pip3 install checkov
RUN PIP_TRUSTED_HOSTASDF=test pip install checkov
RUN ASDFPIP_TRUSTED_HOST=test pip install checkov
RUN echo PIP_TRUSTED_HOST | pip install checkov &&\
    echo "PIP_TRUSTED_HOST"
