name: PR Title

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  validate:
    runs-on: [self-hosted, public, linux, x64]
    permissions:
      contents: write
    steps:
      - uses: thehanimo/pr-title-checker@0cf5902181e78341bb97bb06646396e5bd354b3f  # v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"
