metadata:
  id: "CKV2_AWS_77"
  name: "Ensure AWS API Gateway Rest API attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability"
  category: "NETWORKING"
definition:
  or:
    - and:
      - cond_type: filter
        attribute: resource_type
        operator: within
        value:
          - aws_apigatewayv2_api
          - aws_api_gateway_stage
      - cond_type: connection
        resource_types:
          - aws_apigatewayv2_api
          - aws_api_gateway_stage
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: not_exists
    - and:
      - cond_type: filter
        attribute: resource_type
        operator: within
        value:
          - aws_apigatewayv2_api
          - aws_api_gateway_stage
      - cond_type: connection
        resource_types:
          - aws_apigatewayv2_api
          - aws_api_gateway_stage
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: exists
      - cond_type: connection
        resource_types:
          - aws_wafv2_web_acl
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: exists
      - cond_type: attribute
        resource_types:
          - aws_wafv2_web_acl
        attribute: rule.*.statement.managed_rule_group_statement.name
        operator: contains
        value: "AWSManagedRulesAnonymousIpList"
      - cond_type: attribute
        resource_types:
          - aws_wafv2_web_acl
        attribute: rule.*.statement.managed_rule_group_statement.name
        operator: contains
        value: "AWSManagedRulesKnownBadInputsRuleSet"
