metadata:
  id: "CKV2_AWS_78"
  name: "Ensure AWS AppSync attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability"
  category: "NETWORKING"
definition:
  or:
    - and:
      - cond_type: filter
        attribute: resource_type
        operator: within
        value:
          - aws_appsync_graphql_api
      - cond_type: connection
        resource_types:
          - aws_appsync_graphql_api
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: not_exists
    - and:
      - cond_type: filter
        attribute: resource_type
        operator: within
        value:
          - aws_appsync_graphql_api
      - cond_type: connection
        resource_types:
          - aws_appsync_graphql_api
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: exists
      - cond_type: connection
        resource_types:
          - aws_wafv2_web_acl
        connected_resource_types:
          - aws_wafv2_web_acl_association
        operator: exists
      - cond_type: attribute
        resource_types:
          - aws_wafv2_web_acl
        attribute: rule.*.statement.managed_rule_group_statement.name
        operator: contains
        value: "AWSManagedRulesAnonymousIpList"
      - cond_type: attribute
        resource_types:
          - aws_wafv2_web_acl
        attribute: rule.*.statement.managed_rule_group_statement.name
        operator: contains
        value: "AWSManagedRulesKnownBadInputsRuleSet"
