metadata:
  id: "CKV2_AWS_46"
  name: "Ensure AWS Cloudfront Distribution with S3 have Origin Access set to enabled"
  category: "IAM"
definition:
  or:
    - cond_type: attribute
      resource_types:
        - aws_cloudfront_distribution
      attribute: "origin.*.domain_name"
      operator: not_contains
      value: "aws_s3_bucket."
    - cond_type: attribute
      resource_types:
        - aws_cloudfront_distribution
      attribute: "origin.*.s3_origin_config"
      operator: "exists"
    - cond_type: attribute
      resource_types:
        - aws_cloudfront_distribution
      attribute: "origin.*.origin_access_control_id"
      operator: "exists"         
