metadata:
  id: "CKV2_AWS_47"
  name: "Ensure AWS CloudFront attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability"
  category: "APPLICATION_SECURITY"
definition:
  and:
    - cond_type: filter
      attribute: resource_type
      operator: within
      value:
        - aws_cloudfront_distribution
    - cond_type: connection
      resource_types:
        - aws_cloudfront_distribution
      connected_resource_types:
        - aws_wafv2_web_acl
      operator: exists
    - cond_type: attribute
      resource_types:
        - aws_wafv2_web_acl
      attribute: rule.*.statement.managed_rule_group_statement.name
      operator: contains
      value: "AWSManagedRulesAnonymousIpList"
    - cond_type: attribute
      resource_types:
        - aws_wafv2_web_acl
      attribute: rule.*.statement.managed_rule_group_statement.name
      operator: contains
      value: "AWSManagedRulesKnownBadInputsRuleSet"
      