metadata:
  id: "CKV2_AWS_50"
  name: "Ensure AWS ElastiCache Redis cluster with Multi-AZ Automatic Failover feature set to enabled"
  category: "GENERAL"
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_elasticache_replication_group"
  attribute: "automatic_failover_enabled"
  operator: "equals"
  value: "true"