metadata:
  name: "Ensure that S3 bucket has cross-region replication enabled"
  category: "GENERAL_SECURITY"
  id: "CKV_AWS_144"
definition:
  or:
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: equals
      value: Enabled
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: starting_with
      value: "module."
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: starting_with
      value: "data."
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: starting_with
      value: "var."
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: starting_with
      value: "local."
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: starting_with
      value: "\"${"
    - and:
        - cond_type: filter
          attribute: resource_type
          operator: within
          value:
            - aws_s3_bucket
        - cond_type: connection
          resource_types:
            - aws_s3_bucket
          connected_resource_types:
            - aws_s3_bucket_replication_configuration
          operator: exists
        - or:
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: starting_with
              value: "module."
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: starting_with
              value: "data."
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: starting_with
              value: "var."
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: starting_with
              value: "local."
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: starting_with
              value: "\"${"
            - cond_type: attribute
              resource_types:
                - aws_s3_bucket_replication_configuration
              attribute: rule.*.status
              operator: equals
              value: Enabled
