metadata:
  name: "Ensure that S3 bucket has cross-region replication enabled"
  category: "GENERAL_SECURITY"
  id: "CKV_AWS_144"
definition:
  or:
    - cond_type: attribute
      resource_types:
        - aws_s3_bucket
      attribute: replication_configuration.rules.*.status
      operator: equals
      value: Enabled
    - and:
        - cond_type: filter
          attribute: resource_type
          operator: within
          value:
            - aws_s3_bucket
        - cond_type: connection
          resource_types:
            - aws_s3_bucket
          connected_resource_types:
            - aws_s3_bucket_replication_configuration
          operator: exists
        - cond_type: attribute
          resource_types:
            - aws_s3_bucket_replication_configuration
          attribute: rule.*.status
          operator: equals
          value: Enabled
